import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from './provider'
import { ColorModeScript } from '@chakra-ui/react'
import { Theme } from "@/theme/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trust chain ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
      <ColorModeScript initialColorMode={Theme.config.initialColorMode} />
         <Providers>{children}</Providers></body>
    </html>
  );
}
